! Winteracter resource include file created : 06/Feb/2006 16:17:41
!
      INTEGER, PARAMETER :: ID_ITEM1                        = 40001
      INTEGER, PARAMETER :: IDR_MENU1                       = 30001
      INTEGER, PARAMETER :: ID_HELP_ABOUT                   = 40002
      INTEGER, PARAMETER :: ID_HELP_MANUAL                  = 40005
      INTEGER, PARAMETER :: IDD_ABOUT                       =   101
      INTEGER, PARAMETER :: IDF_LABEL1                      =  1001
      INTEGER, PARAMETER :: ID_ITEM4                        = 40003
      INTEGER, PARAMETER :: IDF_INT1                        =  1885
      INTEGER, PARAMETER :: IDD_EDITFONT                    =   199
