cd\WINOPT_IVF
DEL *.PRF
DEL RESOLVE.DAT
del KDP2.exe
del KDP.exe
DEL CARDTEXT.DAT
DEL EDITTEXT.DAT
DEL RAYS.DAT
DEL psf.DAT
DEL psfbin.dat
DEL PRINTER.DAT
DEL PRINTER.TXT
del rhist.dat
del rhfoot.dat
del psf.dat
del spotter
del fields.dat
del inten.dat
del rayhist.dat
DEL PLOTBMP.BMP
DEL NSSHT.DAT
DEL NSSHIST.DAT
DEL NSSRHIST.DAT
del *.wmf
del *.dxf
del capfnout.dat
del capfnout.bin
del psf.dat
del nssrhist.dat
del nsshist.dat
del nssht.dat
del edittext.dat
del neutral.dat
del libsav.dat
del macsav.dat
del printer.dat
del jim
del vector.dat
del plot99.dat
del plot88.dat
del hpljii.dat
del post.dat
del raster.dat
del apmap.dat
del wamap.dat
del foot1.dat
del opdmap.dat
cd\WINOPT_IVF\SRC
DEL TEMP
del list
del listiss
cd\WINOPT_IVF\libspo
del *.dat
cd\WINOPT_IVF\libplo
del *.dat
cd\WINOPT_IVF
