! Winteracter resource include file created : 06/Feb/2006 16:16:29
!
      INTEGER, PARAMETER :: ID_ITEM1                        = 40001
      INTEGER, PARAMETER :: IDR_MENU1                       = 30001
      INTEGER, PARAMETER :: ID_HELP_ABOUT                   = 40002
      INTEGER, PARAMETER :: IDD_ABOUT                       =   101
      INTEGER, PARAMETER :: IDF_LABEL1                      =  1001
      INTEGER, PARAMETER :: ID_HELP_MANUAL                  = 40003
