        SUBROUTINE CURVATURE_FRESH(J,TEMPCV)
        USE WINTERACTER
        IMPLICIT NONE
        INTEGER J
        REAL*8 TEMPCV
        INCLUDE 'RESOURCE.INC'
        INCLUDE 'DATLEN.INC'
        INCLUDE 'DATMAC.INC'
        INCLUDE 'DATMAI.INC'
        IF(RDM)
     1  CALL WDIALOGSELECT(IDD_SRADIUS)
        IF(.NOT.RDM)
     1  CALL WDIALOGSELECT(IDD_SCURVATURE)
        CALL WDIALOGPUTINTEGER(IDF_SURFNUM,J)
C
C       IF RDM
        IF(RDM) THEN
        CALL WDIALOGPUTCHECKBOX(IDF_MODE1,1)
        CALL WDIALOGPUTCHECKBOX(IDF_MODE2,0)
        IF(ALENS(1,J).NE.0.0D0) TEMPCV=1.0D0/ALENS(1,J)
        IF(ALENS(1,J).EQ.0.0D0) TEMPCV=0.0D0
        CALL WDIALOGPUTDOUBLE(IDF_VAL,TEMPCV,'(G23.15E2)')
C       CURVATURE MODE
                        ELSE
        CALL WDIALOGPUTCHECKBOX(IDF_MODE1,0)
        CALL WDIALOGPUTCHECKBOX(IDF_MODE2,1)
        TEMPCV=ALENS(1,J)
        CALL WDIALOGPUTDOUBLE(IDF_VAL,TEMPCV,'(G23.15E2)')
                        END IF
        CALL WDialogShow(-1,-1,0,Modeless)
                        RETURN
                        END
